// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


let answerDisplay = document.querySelector('.answer') ;
let limite = 4000000

let sumEvenValued = 0;

(function fibonacci(a,b) {
    let fiboA = a;
    let fiboB = b;
    let fiboArray = []
    while (fiboB < limite) {
        console.log(`fiboA: ${fiboA} \n fiboB: ${fiboB} \n Sumatoria de pares: ${sumEvenValued} \n La serie quedaria: ${fiboArray} `)
        
        if (fiboB%2 == 0){
            sumEvenValued += fiboB;
        }
        fiboA = [fiboB, fiboB=fiboA][0];
        fiboB = fiboA + fiboB;
        fiboArray.push(fiboB)
    }
    answerDisplay.innerText = sumEvenValued;
})(1,2);
